services:
  phygen.api:
    image: ${DOCKER_REGISTRY-}phygenapi
    container_name: PhyGen.Api
    build:
      context: .
      dockerfile: PhyGen.Api/Dockerfile
  phygen-db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB = PhyGen
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
