services:
  phygen.api:
    image: ${DOCKER_REGISTRY-}phygenapi
    container_name: PhyGen.Api
    build:
      context: .
      dockerfile: PhyGen.Api/Dockerfile
    ports:
      - "5152:8080"
      - "7165:8081"
    command: ["dotnet", "PhyGen.Api.dll", "--urls=http://0.0.0.0:8080"]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
