services:
  phygen.api:
    image: ${DOCKER_REGISTRY-}phygenapi
    container_name: PhyGen.Api
    build:
      context: .
      dockerfile: PhyGen.Api/Dockerfile
    ports:
      - "5152:8080"
      - "7165:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
